# Generated by Django 5.2 on 2025-04-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_historicaluser_username_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
