# Generated by Django 5.2 on 2025-04-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_make_description_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhook',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook', 'verbose_name_plural': 'Webhooks'},
        ),
        migrations.AddField(
            model_name='historicalwebhook',
            name='last_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebhook',
            name='last_delivery_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwebhook',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the webhook'),
        ),
        migrations.AlterField(
            model_name='historicalwebhook',
            name='events',
            field=models.JSONField(help_text='List of events this webhook is subscribed to'),
        ),
        migrations.AlterField(
            model_name='historicalwebhook',
            name='secret',
            field=models.CharField(blank=True, help_text='Optional secret for webhook authentication', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='events',
            field=models.JSONField(help_text='List of events this webhook is subscribed to'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, help_text='Optional secret for webhook authentication', max_length=255),
        ),
    ]
