# Generated by Django 5.2 on 2025-04-18 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('security_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsecuritygroup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsecuritygroup',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='historicalsecurityrule',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitygroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_groups', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='historicalsecurityrule',
            name='security_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='security_groups.securitygroup'),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='security_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='security_groups.securitygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='securitygroup',
            unique_together={('name', 'organization')},
        ),
    ]
