# Generated by Django 5.2 on 2025-04-18 08:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_update_firewall_model'),
        ('security_groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityrule',
            name='security_group',
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('any', 'Any Protocol')], default='tcp', help_text='Network protocol this rule applies to', max_length=10)),
                ('port_min', models.IntegerField(blank=True, help_text='Starting port (inclusive)', null=True)),
                ('port_max', models.IntegerField(blank=True, help_text='Ending port (inclusive)', null=True)),
                ('source_cidr', models.CharField(default='0.0.0.0/0', help_text='Source CIDR block', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, help_text='Node this rule applies to (if not attached to a security group)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='nodes.node')),
                ('security_group', models.ForeignKey(blank=True, help_text='Security group this rule applies to (if not attached to a specific node)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='security_groups.securitygroup')),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFirewallRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('any', 'Any Protocol')], default='tcp', help_text='Network protocol this rule applies to', max_length=10)),
                ('port_min', models.IntegerField(blank=True, help_text='Starting port (inclusive)', null=True)),
                ('port_max', models.IntegerField(blank=True, help_text='Ending port (inclusive)', null=True)),
                ('source_cidr', models.CharField(default='0.0.0.0/0', help_text='Source CIDR block', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, db_constraint=False, help_text='Node this rule applies to (if not attached to a security group)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nodes.node')),
                ('security_group', models.ForeignKey(blank=True, db_constraint=False, help_text='Security group this rule applies to (if not attached to a specific node)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='security_groups.securitygroup')),
            ],
            options={
                'verbose_name': 'historical Firewall Rule',
                'verbose_name_plural': 'historical Firewall Rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalSecurityRule',
        ),
        migrations.DeleteModel(
            name='SecurityRule',
        ),
    ]
