# Generated by Django 5.2 on 2025-04-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_fix_security_group_relationship'),
        ('security_groups', '0003_update_firewall_model'),
    ]

    # This migration is a no-op state operation to reconcile Django's migration state
    # with the existing database schema which already has the FirewallRule model
    # with all required fields including node_id.
    operations = [
        migrations.SeparateDatabaseAndState(
            # No database operations as the schema matches what we need
            database_operations=[],
            
            # No state operations as the model already exists in Django's state
            state_operations=[]
        ),
    ]
