# Generated by Django 5.2 on 2025-04-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_historicalnode_external_port_historicalnode_fqdn_and_more'),
        ('security_groups', '0004_update_firewall_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='source_groups',
            field=models.ManyToManyField(blank=True, help_text='Source security groups allowed by this rule', related_name='rules_as_source', to='security_groups.securitygroup'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='source_nodes',
            field=models.ManyToManyField(blank=True, help_text='Source nodes allowed by this rule', related_name='rules_as_source', to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='source_cidr',
            field=models.CharField(blank=True, default='', help_text='Source CIDR block (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalfirewallrule',
            name='source_cidr',
            field=models.CharField(blank=True, default='', help_text='Source CIDR block (optional)', max_length=50),
        ),
    ]
