# Generated by Django 5.2.12 on 2026-03-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_invitation_unique_together_and_more'),
        ('security_groups', '0005_firewallrule_source_groups_firewallrule_source_nodes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securitygroup',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='securitygroup',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_sg_name_org'),
        ),
    ]
