# Generated by Django 5.2.14 on 2026-06-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_groups', '0007_rename_securitygroup_to_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='direction',
            field=models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], default='in', help_text='Inbound rules gate traffic INTO the target; outbound gates traffic OUT.', max_length=3),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='match_type',
            field=models.CharField(choices=[('groups', 'Tags'), ('host', 'Host/Node'), ('cidr', 'CIDR'), ('any', 'Any')], default='any', help_text='Which source/destination field is authoritative.', max_length=6),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='Tags whose nodes this rule applies TO (replaces the single security_group FK).', related_name='rules_targeting', to='security_groups.tag'),
        ),
        migrations.AddField(
            model_name='historicalfirewallrule',
            name='direction',
            field=models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], default='in', help_text='Inbound rules gate traffic INTO the target; outbound gates traffic OUT.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalfirewallrule',
            name='match_type',
            field=models.CharField(choices=[('groups', 'Tags'), ('host', 'Host/Node'), ('cidr', 'CIDR'), ('any', 'Any')], default='any', help_text='Which source/destination field is authoritative.', max_length=6),
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
