# Generated by Django 5.2.14 on 2026-06-21 02:45

from django.db import migrations


def forwards(apps, schema_editor):
    FirewallRule = apps.get_model('security_groups', 'FirewallRule')
    from security_groups.migrations._backfill_helpers import backfill_rule
    for rule in FirewallRule.objects.all():
        backfill_rule(rule)


def backwards(apps, schema_editor):
    # target_groups/match_type/direction are additive; nothing to undo destructively.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('security_groups', '0008_add_direction_matchtype_targetgroups_color'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
