# Generated by Django 5.2.15 on 2026-06-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_groups', '0009_backfill_rule_targets_and_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='managed_by_recipe',
            field=models.BooleanField(default=False, help_text='True if this rule was generated by a recipe (regenerated on re-apply).'),
        ),
        migrations.AddField(
            model_name='historicalfirewallrule',
            name='managed_by_recipe',
            field=models.BooleanField(default=False, help_text='True if this rule was generated by a recipe (regenerated on re-apply).'),
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='recipe',
            field=models.CharField(blank=True, default='', help_text='Recipe key whose rules this tag was generated from, if any.', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='recipe_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Stored answers used to generate the recipe rules.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe',
            field=models.CharField(blank=True, default='', help_text='Recipe key whose rules this tag was generated from, if any.', max_length=32),
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Stored answers used to generate the recipe rules.'),
        ),
    ]
