# Generated by Django 5.2 on 2025-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_historicalnetworkrange_networkrange'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1",  # Dummy SQL statement - we've already manually applied the changes
            None,        # No reverse SQL, as we don't want to undo the changes
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
