# Generated by Django 5.2.12 on 2026-03-19 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_historicalorganization_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='networkrange',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('organization', 'email', 'status'), name='unique_org_email_status'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_org'),
        ),
        migrations.AddConstraint(
            model_name='networkrange',
            constraint=models.UniqueConstraint(fields=('organization', 'cidr'), name='unique_org_cidr'),
        ),
    ]
