# Generated by Django 5.2.15 on 2026-07-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_invitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Custom Nebula config keys deep-merged into every generated node config for this org (e.g. {"punchy": {"respond": true}}). The "pki" key is protected and ignored.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Custom Nebula config keys deep-merged into every generated node config for this org (e.g. {"punchy": {"respond": true}}). The "pki" key is protected and ignored.'),
        ),
    ]
