# Generated by Django 5.2.11 on 2026-02-15 00:25

import certificates.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='ca_cert',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data/certs'), upload_to=certificates.models.ca_cert_path),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='ca_key',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data/certs'), upload_to=certificates.models.ca_key_path),
        ),
    ]
