# Generated by Django 5.2.12 on 2026-03-19 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificateauthorityqrcode'),
        ('organizations', '0008_alter_invitation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificateauthority',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='certificateauthority',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_ca_name_org'),
        ),
    ]
