"""
Django settings for open_cvpn project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.core.files.storage import FileSystemStorage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv('DJANGO_SECRET_KEY')
if not _secret_key:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY environment variable is not set. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']  # Configure appropriately in production

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'simple_history',
    'storages',
    'drf_spectacular',
    'axes',

    # Local apps
    'users',
    'organizations',
    'certificates',
    'nodes',
    'security_groups',
    'webhooks',
    'dashboard',
    'health',
    'docs.apps.DocsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'open_cvpn.middleware.APIErrorMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'open_cvpn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'open_cvpn.context_processors.project_meta',  # Catalyst Networks theme
                'open_cvpn.context_processors.breadcrumb_navigation',  # Breadcrumb navigation
            ],
        },
    },
]

WSGI_APPLICATION = 'open_cvpn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if DATABASE_URL is provided (used in production)
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # Production will override this with parsed DATABASE_URL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
        }
    }
else:
    # Development uses individual environment variables
    import warnings
    if not os.getenv('POSTGRES_HOST'):
        warnings.warn(
            "POSTGRES_HOST not set! Database operations will fail.\n"
            "Set POSTGRES_HOST, POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD environment variables."
        )
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST'),
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Dedicated certificate/key storage (can be the same as MEDIA by default)
CERT_STORAGE_ROOT = os.getenv('CERT_STORAGE_ROOT', MEDIA_ROOT)
CERT_STORAGE = FileSystemStorage(location=CERT_STORAGE_ROOT)

# Email settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# Mailgun settings
MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY')
MAILGUN_DOMAIN = os.getenv('MAILGUN_DOMAIN')
if MAILGUN_API_KEY and MAILGUN_DOMAIN:
    EMAIL_BACKEND = 'django_mailgun.MailgunBackend'
    MAILGUN_ACCESS_KEY = MAILGUN_API_KEY
    MAILGUN_SERVER_NAME = MAILGUN_DOMAIN

# Site URL settings
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
if BASE_URL.endswith('/'):
    BASE_URL = BASE_URL[:-1]

# Project Metadata - catalyst_network branding
PROJECT_METADATA = {
    "NAME": "catalyst_network",
    "URL": BASE_URL,
    "DESCRIPTION": "catalyst_network is an advanced mesh network management system for enterprise-grade network security.",
    "IMAGE": "",  # Temporarily disabled to avoid static file errors
    "KEYWORDS": "vpn management, nebula vpn, network security, enterprise security, node management",
    "CONTACT_EMAIL": DEFAULT_FROM_EMAIL,
}

# Update email subject prefix with branding
EMAIL_SUBJECT_PREFIX = "[catalyst_network] "

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'nodes.authentication.NodeAPITokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'open_cvpn.exception_handlers.custom_exception_handler',
}

# Spectacular settings for OpenAPI documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'catalyst_network API',
    'DESCRIPTION': 'The catalyst_network API supports node provisioning and runtime actions for the customer administration platform.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SWAGGER_UI_SETTINGS': {
        'displayOperationId': True,
        'displayRequestDuration': True,
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
        'requestSnippetsEnabled': True,
        'syntaxHighlight.activate': True,
        'syntaxHighlight.theme': 'agate',
        'docExpansion': 'list',
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'displayRequestDuration': True,
        'persistAuthorization': True,
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'hideHostname': False,
        'hideLoading': False,
        'nativeScrollbars': False,
        'disableSearch': False,
        'onlyRequiredInSamples': False,
    },
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums'
    ],
    'EXTENSIONS_INFO': {
        'x-logo': {
            'url': '/static/images/favicons/catalyst-favicon.svg',
            'altText': 'Catalyst Networks API'
        }
    },
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 5))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 1))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY', SECRET_KEY),
}

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Celery settings
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Storage settings (for S3/MinIO - commented out by default)
# To enable S3 storage, set AWS_STORAGE_BUCKET_NAME and configure in settings-prod.py
# which uses the STORAGES dict (Django 5.2+):
#     STORAGES["default"]["BACKEND"] = "storages.backends.s3boto3.S3Boto3Storage"

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Node Registration Settings
_registration_token = os.getenv('REGISTRATION_MASTER_TOKEN')
if not _registration_token:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "REGISTRATION_MASTER_TOKEN environment variable is not set. "
        "Generate a secure token with: python -c \"import secrets; print(secrets.token_urlsafe(32))\""
    )
REGISTRATION_MASTER_TOKEN = _registration_token

# Certificate renewal settings
CERTIFICATE_RENEWAL_WINDOW_DAYS = 14  # Renew certificates 14 days before expiration
CERTIFICATE_RENEWAL_BATCH_SIZE = 10   # Process renewal in batches of 10 nodes
CERTIFICATE_EXPIRY_NOTIFICATION_DAYS = 30  # Notify about expiring certificates 30 days in advance

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'nodes': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'organizations': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Authentication backends (axes must be first for rate limiting)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Django Axes - login rate limiting
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 0.5  # Lock for 30 minutes (in hours)
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # Lock by both username and IP
AXES_RESET_ON_SUCCESS = True  # Reset failed count on successful login
AXES_ENABLE_ACCESS_FAILURE_LOG = True  # Log failed attempts
