# Generated by Django 5.2 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='allauth_app_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_allowed_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_client_id',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_client_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_display_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_email_claim',
            field=models.CharField(default='email', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_first_name_claim',
            field=models.CharField(default='given_name', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_issuer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_last_name_claim',
            field=models.CharField(default='family_name', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_mode',
            field=models.CharField(blank=True, choices=[('google', 'Google Workspace'), ('generic', 'Generic OIDC')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_provider_id',
            field=models.SlugField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_scopes',
            field=models.CharField(default='openid email profile', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='oidc_subject_claim',
            field=models.CharField(default='sub', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalssoconfiguration',
            name='provider_type',
            field=models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC / Google')], default='saml', max_length=20),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='allauth_app_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_allowed_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_client_id',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_client_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_display_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_email_claim',
            field=models.CharField(default='email', max_length=80),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_first_name_claim',
            field=models.CharField(default='given_name', max_length=80),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_issuer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_last_name_claim',
            field=models.CharField(default='family_name', max_length=80),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_mode',
            field=models.CharField(blank=True, choices=[('google', 'Google Workspace'), ('generic', 'Generic OIDC')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_provider_id',
            field=models.SlugField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_scopes',
            field=models.CharField(default='openid email profile', max_length=255),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='oidc_subject_claim',
            field=models.CharField(default='sub', max_length=80),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='provider_type',
            field=models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC / Google')], default='saml', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalssoconfiguration',
            name='idp_entity_id',
            field=models.CharField(blank=True, default='', help_text='IdP Entity ID (Issuer URL)', max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalssoconfiguration',
            name='idp_sso_url',
            field=models.URLField(blank=True, default='', help_text='IdP Single Sign-On URL', max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalssoconfiguration',
            name='idp_x509_cert',
            field=models.TextField(blank=True, default='', help_text='IdP X.509 certificate (PEM format, without header/footer)'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='idp_entity_id',
            field=models.CharField(blank=True, default='', help_text='IdP Entity ID (Issuer URL)', max_length=512),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='idp_sso_url',
            field=models.URLField(blank=True, default='', help_text='IdP Single Sign-On URL', max_length=512),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='idp_x509_cert',
            field=models.TextField(blank=True, default='', help_text='IdP X.509 certificate (PEM format, without header/footer)'),
        ),
    ]
