# Generated by Django 5.2 on 2025-04-18 02:34

import django.db.models.deletion
import nodes.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('organizations', '0003_alter_membership_options_alter_organization_options_and_more'),
        ('security_groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nebula_ip', models.GenericIPAddressField(db_index=True, help_text='IP address in the Nebula network', protocol='IPv4')),
                ('cert', models.TextField(max_length=100)),
                ('key', models.TextField(max_length=100)),
                ('cert_expiration', models.DateTimeField()),
                ('is_lighthouse', models.BooleanField(default=False, help_text='Whether this node acts as a lighthouse')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('certificate_authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certificates.certificateauthority')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical Node',
                'verbose_name_plural': 'historical Nodes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nebula_ip', models.GenericIPAddressField(help_text='IP address in the Nebula network', protocol='IPv4', unique=True)),
                ('cert', models.FileField(upload_to=nodes.models.node_cert_path)),
                ('key', models.FileField(upload_to=nodes.models.node_key_path)),
                ('cert_expiration', models.DateTimeField()),
                ('is_lighthouse', models.BooleanField(default=False, help_text='Whether this node acts as a lighthouse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='certificates.certificateauthority')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='organizations.organization')),
                ('security_groups', models.ManyToManyField(related_name='nodes', to='security_groups.securitygroup')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'unique_together': {('name', 'organization')},
            },
        ),
    ]
