# Generated by Django 5.2 on 2025-04-18 03:55

import django.db.models.deletion
import django.utils.timezone
import nodes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('nodes', '0001_initial'),
        ('security_groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['-created_at'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalnode',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='historicalnode',
            name='key',
        ),
        migrations.AddField(
            model_name='historicalnode',
            name='cert_path',
            field=models.TextField(blank=True, help_text="Path to the node's certificate", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalnode',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this node', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnode',
            name='key_path',
            field=models.TextField(blank=True, help_text="Path to the node's private key", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='cert_path',
            field=models.FileField(blank=True, help_text="Path to the node's certificate", null=True, upload_to=nodes.models.node_cert_path),
        ),
        migrations.AddField(
            model_name='node',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='key_path',
            field=models.FileField(blank=True, help_text="Path to the node's private key", null=True, upload_to=nodes.models.node_key_path),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='cert_expiration',
            field=models.DateTimeField(blank=True, help_text='Certificate expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='is_lighthouse',
            field=models.BooleanField(default=False, help_text='Whether this node is a lighthouse'),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='name',
            field=models.CharField(help_text='Hostname or description of the node', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='nebula_ip',
            field=models.GenericIPAddressField(db_index=True, help_text="IP address in the organization's network range"),
        ),
        migrations.AlterField(
            model_name='node',
            name='cert_expiration',
            field=models.DateTimeField(blank=True, help_text='Certificate expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='certificate_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='certificates.certificateauthority'),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='node',
            name='is_lighthouse',
            field=models.BooleanField(default=False, help_text='Whether this node is a lighthouse'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(help_text='Hostname or description of the node', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='nebula_ip',
            field=models.GenericIPAddressField(help_text="IP address in the organization's network range", unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='security_groups',
            field=models.ManyToManyField(blank=True, help_text='Security groups this node belongs to', related_name='nodes', to='security_groups.securitygroup'),
        ),
        migrations.RemoveField(
            model_name='node',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='node',
            name='key',
        ),
    ]
