# Generated by Django 5.2 on 2025-04-18 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('nodes', '0002_alter_node_options_alter_node_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='security_groups',
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user who created this node', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='nebula_ip',
            field=models.CharField(help_text="IP address in the organization's network range", max_length=45),
        ),
        migrations.AlterField(
            model_name='node',
            name='certificate_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='certificates.certificateauthority'),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='node',
            name='nebula_ip',
            field=models.CharField(help_text="IP address in the organization's network range", max_length=45),
        ),
    ]
