# Generated by Django 5.2 on 2025-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_remove_node_security_groups_and_more'),
        ('security_groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='security_groups',
            field=models.ManyToManyField(blank=True, help_text='Security groups this node belongs to', related_name='nodes', to='security_groups.securitygroup'),
        ),
    ]
