# Generated by Django 5.2 on 2025-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_node_security_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnode',
            name='nebula_ip',
            field=models.CharField(blank=True, help_text="IP address in the organization's network range", max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='nebula_ip',
            field=models.CharField(blank=True, help_text="IP address in the organization's network range", max_length=45, null=True),
        ),
    ]
