# Generated by Django 5.2 on 2025-04-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_noderegistrationtoken'),
        ('security_groups', '0002_initial'),  # Make sure to include the security_groups dependency
    ]

    operations = [
        # Remove the existing relationship table
        migrations.RemoveField(
            model_name='node',
            name='security_groups',
        ),
        # Recreate the many-to-many relationship
        migrations.AddField(
            model_name='node',
            name='security_groups',
            field=models.ManyToManyField(
                blank=True, 
                help_text='Security groups this node belongs to',
                related_name='nodes',
                to='security_groups.securitygroup'
            ),
        ),
    ]
