# Generated by Django 5.2 on 2025-04-18 08:22

import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_fix_security_group_relationship'),
        ('security_groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnode',
            name='nebula_ip',
            field=models.GenericIPAddressField(default='192.168.1.1', help_text="IP address in the organization's network range"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='nebula_ip',
            field=models.GenericIPAddressField(default='192.168.1.1', help_text="IP address in the organization's network range"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='security_groups',
            field=models.ManyToManyField(blank=True, help_text='Security groups this node belongs to (simple collections of nodes)', related_name='nodes', to='security_groups.securitygroup'),
        ),
        migrations.AlterField(
            model_name='noderegistrationtoken',
            name='token',
            field=models.CharField(default=nodes.models.generate_token, help_text='Unique token for node registration', max_length=255, unique=True),
        ),
    ]
