# Generated by Django 5.2 on 2025-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_update_firewall_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='external_port',
            field=models.IntegerField(default=4242, help_text='External port for lighthouse nodes'),
        ),
        migrations.AddField(
            model_name='historicalnode',
            name='fqdn',
            field=models.CharField(blank=True, help_text='Fully Qualified Domain Name for lighthouse nodes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalnode',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Public IP address for lighthouse nodes', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='external_port',
            field=models.IntegerField(default=4242, help_text='External port for lighthouse nodes'),
        ),
        migrations.AddField(
            model_name='node',
            name='fqdn',
            field=models.CharField(blank=True, help_text='Fully Qualified Domain Name for lighthouse nodes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Public IP address for lighthouse nodes', null=True),
        ),
    ]
