# Generated by Django 5.2 on 2025-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_historicalnode_external_port_historicalnode_fqdn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderegistrationtoken',
            name='can_register_lighthouse',
            field=models.BooleanField(default=False, help_text='Whether this token can register lighthouse nodes'),
        ),
        migrations.AddField(
            model_name='noderegistrationtoken',
            name='can_register_regular',
            field=models.BooleanField(default=True, help_text='Whether this token can register regular nodes'),
        ),
    ]
