# Generated by Django 5.2 on 2025-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_noderegistrationtoken_can_register_lighthouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique API token for authenticating this nodes API requests', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='api_token',
            field=models.CharField(blank=True, help_text='Unique API token for authenticating this nodes API requests', max_length=64, null=True, unique=True),
        ),
    ]
