# Generated by Django 5.2 on 2025-04-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_historicalnode_api_token_node_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='last_checkin',
            field=models.DateTimeField(blank=True, help_text='Last time this node checked in via API', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_checkin',
            field=models.DateTimeField(blank=True, help_text='Last time this node checked in via API', null=True),
        ),
    ]
