# Generated by Django 5.2.11 on 2026-02-15 00:25

import django.core.files.storage
import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0013_nodeqr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='cert_path',
            field=models.FileField(blank=True, help_text="Path to the node's certificate", null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/certs'), upload_to=nodes.models.node_cert_path),
        ),
        migrations.AlterField(
            model_name='node',
            name='key_path',
            field=models.FileField(blank=True, help_text="Path to the node's private key", null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/certs'), upload_to=nodes.models.node_key_path),
        ),
        migrations.AlterField(
            model_name='nodeqrcode',
            name='qr_image',
            field=models.ImageField(help_text='Generated QR code image file', upload_to=nodes.models.node_qr_path),
        ),
    ]
