# Generated by Django 5.2.15 on 2026-07-06 00:26

import django.core.files.storage
import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0018_rename_securitygroup_to_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Custom Nebula config keys deep-merged into this node\'s generated config, on top of any org-level overrides. The "pki" key is protected and ignored.'),
        ),
        migrations.AddField(
            model_name='node',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Custom Nebula config keys deep-merged into this node\'s generated config, on top of any org-level overrides. The "pki" key is protected and ignored.'),
        ),
    ]
